package tests.ambrasiunas;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import metasite.task.ambrasiunas.Application;
import metasite.task.ambrasiunas.services.FileProcessingService;
import metasite.task.ambrasiunas.services.UserCatalogService;
import org.junit.Before;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

@RunWith(SpringRunner.class)
@SpringBootTest
@AutoConfigureMockMvc
@ContextConfiguration(classes = {Application.class})
public class ContextBase {

    public final Logger logger = LoggerFactory.getLogger(ContextBase.class);

    @Autowired
    public UserCatalogService userCatalogService;

    @Autowired
    public FileProcessingService fileProcessingService;

    @Autowired
    public MockMvc mockMvc;

    @Autowired
    public ObjectMapper objectMapper;

    public final String testFileContent = "Some content for the file that is being generated by this test1 and has alphabetic " +
            "words begining within a range that is required for this task. Words with z letter like zoo and v like voice or even" +
            "words like h like human and n like number and in some cases it has to be in between a and g with words like age and gun5!" +
            "also this skips special characters and such like th1s word with numbers51251 at the end.";

    @Before
    public void setUp() throws Exception {
        this.objectMapper.disable(MapperFeature.DEFAULT_VIEW_INCLUSION);
        this.objectMapper.findAndRegisterModules();
        this.objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    }
}
